Multiple dags
Unity-Technologies/tundra pull request #19
Opened 2018-07-28 21:05 UTC by lucasmeijer

For each node in the buildstate, store an array of dag identifiers in which we've seen this node. Once we run a build from a dag which used to have a certain node, we delete the node. This allows unity like
deployments where the buildprogram can generate many different dags that all need to operate on the same buildstate.

2018-07-28 22:21 UTC, ecuzzillo approved these changes

2018-07-29 03:20 UTC, richard-fine requested changes

2018-07-29 03:20 UTC, richard-fine commented on src/BinaryData.hpp
> +  FrozenArray() {}
Revert this

2018-07-29 03:20 UTC, richard-fine commented on src/Driver.cpp
> +    MemAllocLinear* scratch = &self->m_Allocator;
What's this needed for?

2018-07-29 18:26 UTC, lucasmeijer commented on src/Driver.cpp
> +    MemAllocLinear* scratch = &self->m_Allocator;
further down in the function, in a part not shown in this diff because it's not different,  we use a scratch allocator.   The code removed by this PR was creating the scratch allocator.   Since we still do need it,  it shows up as a green addition here,  but if you look at the red, you can see that it was here all along

2018-07-29 18:30 UTC, richard-fine commented on src/Driver.cpp
> +    MemAllocLinear* scratch = &self->m_Allocator;
Ohh, it was captured from outside the lambda. OK.

2018-07-29 18:30 UTC, richard-fine approved these changes

2018-07-29 19:28 UTC, merged