add support for banning content digest for inputs
Unity-Technologies/tundra pull request #33
Opened 2018-11-02 19:32 UTC by ecuzzillo

because clang on osx complains if the .h timestamps change but we don't rebuild the pch because the content didn't change

2018-11-09 08:39 UTC, richard-fine commented
Please also confirm whether nodes with this behaviour are correctly reported by `bee why`, I think you're missing some logic in the function that reports the reason for the input signature change.

2018-11-09 08:39 UTC, richard-fine requested changes

2018-11-09 08:39 UTC, richard-fine commented on src/FileSign.cpp
> +  if (force_use_timestamp || ShouldUseSHA1SignatureFor(filename, sha_extension_hashes, sha_extension_hash_count))
This looks the wrong way around...

2018-11-09 08:39 UTC, richard-fine commented on src/FileSign.cpp
> +  if (force_use_timestamp || ShouldUseSHA1SignatureFor(filename, sha_extension_hashes, sha_extension_hash_count))
```suggestion
  if (!force_use_timestamp && ShouldUseSHA1SignatureFor(filename, sha_extension_hashes, sha_extension_hash_count))
```

2018-11-26 22:37 UTC, ecuzzillo commented on src/FileSign.cpp
> +  if (force_use_timestamp || ShouldUseSHA1SignatureFor(filename, sha_extension_hashes, sha_extension_hash_count))
fixed in 9263dc0

2018-11-28 18:55 UTC, merged