Fix windows longpath support
Unity-Technologies/tundra pull request #79
Opened 2020-07-22 17:35 UTC by wackoisgod

This PR adds proper Long Path support, that works for the different use cases: 

```
MakeDirectory("C:\\Users\\foo\\source\\repos\\Builds\\");
MakeDirectory("C:\\Users\\foo\\source\\repos\\..\\Builds\\");
MakeDirectory("\\\\?\\C:\\Users\\foo\\source\\repos\\..\\Builds\\");
MakeDirectory("..\\..\\Build\\");
MakeDirectory("..\\..\\BuildssldkfjsdawdawdawxwxwxwxwxwxwxwxwxwxwxwxwxwxwxdawdawdfsdfsdfsdfsdfsdfsdfsdldkjflskjdflskjdflksjdflksjdfBuildssldkfjsldkjflskjdflskjdflksjdflksjdfBuildssldkfjsldkjflskjdflskjdflksjdflksjdfBuildssldkfjsldkjflskjdflskjdflksjdflksjdf\\");
```

These use cases are now properly supported, where before relative paths were just broken, and not properly being resolved which is required when you use the long path prefix. 

The usage of std::wstring makes the code far less complex and more clear whats going on, it also prevents memory leaks or just general bad pointer foo. This code is not in the most critical perf path so I didn't feel like it needed to rely on the underlying LinearAllocator as the standard std::allocator is just wrapping malloc anyways and these are all temp strings anyways and I don't feel like there would be a lot of benefit using the LinearAllocator

2020-08-06 02:17 UTC, richard-fine commented on src/FileInfo.cpp
>      if (strlen(path) >= MAX_PATH)
This is not safe, from what you've told me - a relative path that is less than MAX_PATH chars could expand to a path that is too long once we pass it to the WinAPI.

2020-08-06 15:34 UTC, richard-fine requested changes
One issue raised, plus it needs tests adding.

2020-08-19 03:03 UTC, wackoisgod commented
@richard-fine tests have been added and the unsafe API has been resolved.

2020-08-20 16:23 UTC, richard-fine approved these changes
Alright. I'm still a bit nervous about the performance implications of this, but I think the functionality is sound at least. If we need to optimise later then so be it.

2020-08-20 16:23 UTC, merged